$.i18n().load( {
	en: {
    "menu.education": "Educational Background",
    "menu.experience": "Professional Experience",
    "menu.profile": "Who Am I",
    "menu.select.language": "Languages",
    "menu.click.github": "My git",
    "label.job": "Computer Scientist",
    "info.where":"Born in Ji-Parana, Rondonia and raised in Rio Branco, Acre where I lived for 8 years. Then, I moved out to Grajau City, Maranhao, where I lived until 2008. In 2008 I started my I.T. technician course on CEFET-MA today called IFMA Campus Imperatriz, and it was when my journey towards the computing world begun. After that, I was enrolled in the Computer Science course at Federal University of Tocantins (UFT). Nowadays I live in the city of Palmas, Tocantins where I work as a Java Developer.",
    "info.about":"Due to the various places where I lived in, I consider myself a piece of each City/Province/State, I am mosaic of cultures and I strongly desire to add some more colors to this beautiful mixture. I have a dream to change the world, even though the effect provoked by my change might be minimal I would like trying to bring something relevant through computing.",
    "job.middle.developer": "Middle Software Developer",
    "job.fullStack.developer":"Fullstack Software Developer",
    "job.intern":"Intern",
    "job.owner":"Owner",
    "job.scholarship":"SWB Scholarship",
    "job.company": "Company:",
    "month.january":"January",
    "month.february":"February",
    "month.march":"March",
    "month.april":"April",
    "month.may":"May",
    "month.june":"June",
    "month.july":"July",
    "month.august":"August",
    "month.september":"September",
    "month.october":"October",
    "month.november":"November",
    "month.december":"December",
    "time.now": "Now",
    "sifcon.experience":"Developement of Internal Solutions for Financial Management and other solutions.",
    "fapto.experience":"Development of the project: Cadastro Territorial Urbano e Planta Genérica de Valores de Paraíso do Tocantins.",
    "detran.experience":"New functionalities development, help desk and maintenance of The Help system.",
    "cinneshow.experience":"Movies exhibition according to the trends after DVD release, the purpose was to bring a new concept of fun for the people of Grajau. Selling of popcorn and soda + tickets. The project begun at the Cineteatro São Camilo and it was finished at the High School Nicolau Dino.",
    "capes.experience":"International Exchange where it was offered a Language Training Internship with the duration of 8 months at the Language Training Center from Red River College. After that, the activities for 3rd term for the Business Information Technology course at RRC had begun. The knowledge obtained were and are constantly applied during my career.",
    "bb.experience":"Development of the Superintendence Intranet, internal apps, software maintenance and help desk.",
    "job.technologies":"Technologies:",
    "button.more":"Know More",
    "education.ifma":"I.T. Technician",
    "education.uft":"Computer Science",
    "education.tech":"High-school + technician",
    "education.bachelor":"Undergraduate",
    "education.exchange":"Exchange"
   },
	br: {
      "menu.education": "Educação",
      "menu.experience": "Experiência Profissional",
      "menu.profile": "Quem Sou Eu",
      "menu.select.language": "Idiomas",
      "menu.click.github": "Meu git",
      "label.job": "Cientista da Computação",
      "info.where":"Natural da cidade de Ji-Paraná - RO, morei na cidade de Rio Branco no Acre até os 8 anos de idade e então mudei para a cidade de Grajaú do Maranhão, onde vivi até 2008. No ano de 2008 fui aprovado no CEFET-MA atual IFMA Campus Imperatriz, e lá dei início à minha jornada no mundo da computação como Técnico em Informática e logo em seguida ingressei no Curso de Ciência da Computação na UFT. Atualmente resido na cidade de Palmas e trabalho como Desenvolvedor de Sistemas.",
      "info.about":"Por ter vivido em tantos lugares me considero um pouco de cada um dos Estados/Cidades que já morei, sou um mix de cada cultura e quero incrementar um pouco mais esse mix. Desejo fazer a diferença no mundo, mesmo que a mudança causada seja mínima, gostaria de realizar algo relevante e através da computação.",
      "job.middle.developer": "Desenvolvedor de Software Pleno",
      "job.fullStack.developer":"Desenvolvedor de Software Fullstack",
      "job.intern":"Estagiário",
      "job.owner":"Proprietário",
      "job.scholarship":"Bolsista CSF",
      "job.company": "Empresa:",
      "month.january":"Janeiro",
      "month.february":"Fevereiro",
      "month.march":"Março",
      "month.april":"Abril",
      "month.may":"Maio",
      "month.june":"Junho",
      "month.july":"Julho",
      "month.august":"Agosto",
      "month.september":"Setembro",
      "month.october":"Outubro",
      "month.november":"Novembro",
      "month.december":"Dezembro",
      "time.now": "Atual",
      "sifcon.experience":"Desenvolvimento de sistemas internos para controle financeiro e outras funcionalidades.",
      "fapto.experience":"Desenvolvimento do projeto de Cadastro Territorial Urbano e Planta Genérica de Valores de Paraíso do Tocantins.",
      "detran.experience":"Desenvolvimento de novas funcionalidades, suporte interno e manutenção do sistema de Chamados.",
      "cinneshow.experience":"Exibição de filmes recentes para toda a população Grajauense, oferecendo um novo tipo de entretenimento para a cidade. Venda de pipoca e refrigerante no local. O projeto teve início no Cineteatro São Camilo e foi Concluído no Colégio Nicolau Dino.",
      "capes.experience":"ntercâmbio Internacional no qual foi realizado Estágio Linguístico com duração de 8 meses no Language Training Center do Red River College. Em seguida iniciaram-se as atividades do 3º período de Business Information Technology do RRC. Os conhecimentos obtidos foram e são constantemente utilizados.",
      "bb.experience":"Desenvolvimento da intranet da Superintendência, aplicativos internos, manutenção de softwares internos e suporte interno.",
      "job.technologies":"Tecnologias:",
      "button.more":"Saiba Mais",
      "education.ifma":"Técnico em Informática",
      "education.uft":"Ciência da Computação",
      "education.tech":"Médio-Técnico",
      "education.bachelor":"Graduação",
      "education.exchange":"Intercâmbio"
    }
  });


function languageSelect(language){
    $.i18n( { locale: language } );
    $('[data-i18n]').i18n();
    $('.dropdown').removeClass('open');
    $('.language-icon').attr('src', 'images/'+$.i18n().locale+'.png');
}
